server:
  port: 8006
spring:
  application:
    name: alipay-front

#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka
    register-with-eureka: true
    #是否从eureka抓取已有的注册信息，默认为true,单点无所谓，但是集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #表示入注的位置
    service-url:
      #集群
      defaultZone: http://zpc:123456@eureka7001.com:7001/eureka/,http://zpc:123456@eureka7003.com:7003/eureka/
  #修改主机名称
  instance:
    instance-id: alipyfront8006
    prefer-ip-address: true   #访问路径可以显示ip地址
    #eureka客户端向服务器发送心跳的时间间隔（单位：秒 默认30秒）
    lease-expiration-duration-in-seconds: 30
    #eureka服务端在收到最后一次心跳后等待时间上线（单位：秒 默认90秒） 超时剔除服务
    lease-renewal-interval-in-seconds: 90
